// https://en.wikipedia.org/wiki/Fibonacci_sequence
// https://projecteuler.net/problem=2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million
// Find the sum of the even-valued terms.
export default function fibonacciEven(n) {
  // if (n < 0) return 'Enter a positive integer';
  if (n === 0) return 2;
  if (n === 1) return 8;
  return 4 * fibonacciEven(n - 1) + fibonacciEven(n - 2);
  // const sequence = [0, 1];
}
